/*
 * This source file was generated by the Gradle 'init' task
 */
package board;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import java.sql.SQLException;

class AppTest {
    @Test void appHasAGreeting() throws SQLException {
        Main classUnderTest = new Main();
        Main.main(null);
    }
}
